application: study-group-app
version: 1
runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /
  static_files: www/index.html
  upload: www/index.html
- url: /css
  static_dir: www/css
- url: /templates
  static_dir: www/templates
- url: /js
  static_dir: www/js
- url: /img
  static_dir: www/img
- url: /lib
  static_dir: www/lib

libraries:
- name: webapp2
  version: latest
